---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: etherpad-archive
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: archive
            image: alpine:3.19
            command:
            - sh
            - -c
            - |
              tar cfz /backup/$(date +\%Y\%m\%d).tgz /data
            volumeMounts:
            - name: etherpad-var
              mountPath: /data
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: etherpad-var
            persistentVolumeClaim:
              claimName: etherpad-var
          - name: backup
            persistentVolumeClaim:
              claimName: etherpad-backup
