---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - name: etherpad
        image: etherpad/etherpad:2.0
        ports:
        - containerPort: 9001
        env:
        - name: NODE_ENV
          value: "development"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: etherpad-secret
              key: ADMIN_PASSWORD
        - name: DB_CHARSET
          value: "utf8mb4"
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "etherpad"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PORT
          value: "5432"
        - name: DB_TYPE
          value: "postgres"
        - name: DEFAULT_PAD_TEXT
          value: ""
        - name: DISABLE_IP_LOGGING
          value: "true"
        - name: SOFFICE
          value: ""
        - name: TRUST_PROXY
          value: "true"
        volumeMounts:
        - name: etherpad-var
          mountPath: /opt/etherpad-lite/var
      volumes:
      - name: etherpad-var
        persistentVolumeClaim:
          claimName: etherpad-var
