---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-backup
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.backup.etherpad.storage.size }}
