---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
spec:
  replicas: {{ .Values.etherpad.replicaCount }}
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - name: etherpad
        image: "{{ .Values.etherpad.image.repository }}:{{ .Values.etherpad.image.tag }}"
        ports:
        - containerPort: 9001
        env:
        - name: NODE_ENV
          value: {{ .Values.etherpad.nodeEnv | quote }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: etherpad-secret
              key: ADMIN_PASSWORD
        - name: DB_CHARSET
          value: "utf8mb4"
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: {{ .Values.postgresql.database | quote }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PORT
          value: {{ .Values.postgresql.port | quote }}
        - name: DB_TYPE
          value: "postgres"
        - name: DEFAULT_PAD_TEXT
          value: {{ .Values.etherpad.defaultPadText | quote }}
        - name: DISABLE_IP_LOGGING
          value: {{ .Values.etherpad.disableIpLogging | quote }}
        - name: SOFFICE
          value: {{ .Values.etherpad.soffice | quote }}
        - name: TRUST_PROXY
          value: {{ .Values.etherpad.trustProxy | quote }}
        volumeMounts:
        - name: etherpad-var
          mountPath: /opt/etherpad-lite/var
      volumes:
      - name: etherpad-var
        persistentVolumeClaim:
          claimName: etherpad-var
