---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.backup.postgres.storage.size }}
